import { HeaderBar } from '@/shared/HeaderBar'
import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { RoutingLink } from '@/models/routing/RoutingLink'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const routingLinks: RoutingLink[] = [{ link: 'game', display: 'Play a Game' }]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HeaderBar links={...routingLinks} />
        <div className="children">
          {children}
        </div></body>
    </html >
  )
}
